model:
  name: flowMAR_B_pixel_v_exp_mask
  dataset_name: ImageNet_256
  params:
    img_size: 256
    patch_size: 16
    in_channels: 3
    ema_decay: [0.999, 0.9995, 0.9999]
    t_eps: 5.0e-2
    sample_t_mean: 0.8
    sample_t_std: 0.8
    t_sampling_method: 'logit_normal'
    diffusion_batch_mul: 1
    pred_type: 'v'
    bottleneck_dim: 128
  ar_params:
    ar_type: 'encoder_decoder'
    encoder_dim: 768
    encoder_depth: 6
    encoder_num_heads: 12
    decoder_dim: 768
    decoder_depth: 6
    decoder_num_heads: 12
    mlp_ratio: 4.0
    dropout: 0.1
    class_token_size: 64
    mask_rate_token_size: 8
    train_mask_schedule: 'exp'
    mask_condition: False
    min_s: 0.2
  denoiser_params:
    hidden_dim: 1024
    depth: 6
    hidden_ratio: 4.0
    dropout: 0.0

sampler:
  method: 'euler'
  t_eps_sample: 1.0e-4
  mask_schedule: 'cosine'
  order_strategy: random
  num_ar_steps: 32
  num_timesteps: 50
  noise_scale: 1.0