model:
  name: pixelMar_base_dinov2_256
  dataset_name: ImageNet
  params:
    img_size: 256
    patch_size: 16
    in_channels: 3
    ema_decay: [0.999, 0.9995, 0.9999]
    t_eps: 5.0e-2
    sample_t_mean: 0.0
    sample_t_std: 1.0
    train_shift: 6.93
    sample_shift: 6.93
    t_sampling_method: 'logit_normal'
    diffusion_batch_mul: 1
    pred_type: 'x' 
  rae_params:
    latent_type: 'dinov2'
    latent_dim: 384
    rae_encoder: 'facebook/dinov2-with-registers-small'
    rae_decoder_ckp: './rae_models/dinov2_small/model.pt'
    rae_norm_stats: './rae_models/dinov2_small/stat.pt'
    rae_decoder_config: './src/rae/rae_decoder_configs/ViTXL'
  ar_params:
    ar_type: 'decoder'
    decoder_dim: 384
    decoder_depth: 24
    decoder_num_heads: 6
    mlp_ratio: 4.0
    dropout: 0.1
    class_token_size: 64
    mask_rate_token_size: 8
    gt_noise_scale: 0.2
    train_mask_schedule: 'exp'
    mask_condition: False
    min_s: 0.2
  denoiser_params:
    hidden_dim: 1024
    depth: 6
    dropout: 0.0
    
sampler:
  method: 'euler'
  t_eps_sample: 1.0e-4
  mask_schedule: 'cosine'
  order_strategy: random
  num_ar_steps: 32
  num_timesteps: 50
  noise_scale: 1.0